spring.application.name=Nirvana

##postgresql database configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

## JPA configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

## Spring Security configuration
spring.security.user.name=apurva
spring.security.user.password=nirvana123

##Gemini configuration
gemini.model = gemini-flash-latest
gemini.api.key=${GEMINI_API_KEY}

##jwt configuration
jwt.secret=${JWT_SECRET}

### Optional import of local properties file
#spring.config.import=optional:file:./application-local.properties
# Local configuration


#Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method
spring.mvc.pathmatch.matching-strategy=ant_path_matcher


## Logging configuration
logging.level.org.springdoc=DEBUG
server.error.include-message=always
server.error.include-stacktrace=always

