spring.application.name=Nirvana
spring.datasource.url=jdbc:postgresql://localhost:5432/nirvana_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.security.user.name=apurva
spring.security.user.password=1234
